from models import structured_output_model, get_generation_model,research_structured_output_model, structured_output_model_research
from states import BlogState, EvidencePackSchema, PlanSchema, ResearchSchema
from prompts.generation_prompts import get_blog_planning_prompt, worker_prompt,get_router_prompt, get_evidence_research_prompt
from typing import Dict, List, cast
from langgraph.types import Send, interrupt
from langgraph.errors import GraphInterrupt
from langgraph.graph import END
import httpx

from utils import normalize_tavily_results, perform_research, safe_filename



#  1. get the blog_topic and other details from initial state

async def router_node(state:BlogState) -> dict:
    try:
        print("Router_node : Extracting details from blog description...\n")
        # 1. Get the prompt for detail extraction
        prompt = get_router_prompt(state.user_query)
        # 2. call the structured output model to extract details from blog description
        response = cast(ResearchSchema, await research_structured_output_model.ainvoke(prompt))

        #  return the extracted details to update the state
        print("Router_node : Detail extraction complete.\n")

        return {
            'blog_topic': response.topic, #type: ignore
            # blog_description is not a BlogState field — removed to prevent silent state-validation failure
            'audience': response.audience,  #type: ignore
            'tone': response.tone,  #type: ignore
            'require_research': response.require_research,  #type: ignore
            'research_mode': response.research_mode,  #type: ignore
            'research_queries': response.research_queries, #type: ignore
            'blog_kind': response.blog_kind #type: ignore
            }
    
    except Exception as e:

        print(f"Router_node : Error in router_node: {e}")
        raise e 


# Routing Conditon
def router_condition_func(state: BlogState) -> str:
    if state.require_research:
        return 'research_node'
    else:
        # return END
        return 'orchestrator'


# 2. Research_node
async def research_node(state:BlogState) -> dict:

    # get queries from state
    queries = state.research_queries or []

    raw_result: List[Dict] = []

    for query in queries:
        result = await perform_research(query)
        # result_list_dict.append(result) #type: ignore
        raw_result.extend(result.get("results", []))

    if not raw_result:
        return {'evidence': []}
    
    # 2. Deduplicate by URL (Critical for Production)
    unique_results = {}
    for r in raw_result:
        url = r.get("url")
        if url not in unique_results:
            unique_results[url] = r
    

    deduplicated_list = list(unique_results.values())
    

    # normalize the results into a consistent format for the reducer to consume
    normalized_results = normalize_tavily_results(deduplicated_list)

    # get the prompt for evidence extraction from normalized research results
    evidence_research_prompt = get_evidence_research_prompt(normalized_results) 

    # call the structured output model to extract evidence from research results
    response = cast(EvidencePackSchema, await structured_output_model_research.ainvoke(evidence_research_prompt))

    print("Research_node : Research complete. Evidence collected:\n")

    return {'evidence': response.evidence} #type: ignore



#  3. Orchestration logic for the blog planning process
async def orchestrator(state:BlogState) -> Dict:
    try:
        print("Orchestrator : Generating blog plan...\n")
        # 1. Get the prompt for blog planning
        blog_description = state.user_query
        blog_topic = state.blog_topic
        blog_audience = state.audience
        blog_tone = state.tone
        blog_evidence = state.evidence

        prompt = get_blog_planning_prompt(blog_topic, blog_description, blog_audience, blog_tone, blog_evidence)

        # 2. call the structured output model to generate the plan
        response = cast(PlanSchema, await structured_output_model.ainvoke(prompt))

        # print("Raw response from model:\n\n", response)
        print("Orchestrator : Blog plan generation complete.\n")

        return {'plan': response ,"blog_title": response.blog_title} #type: ignore
    except Exception as e:
        print(f"Orchestrator : Error in generate_blog_plan: {e}")
        raise e

# create worker to parallely execute the tasks in the plan generated by orchestrator
def fanout(state: BlogState) -> List[Send]:
    try:
        if not state.plan or not state.plan.tasks:
            raise ValueError("No plan or tasks found in state")

        tasks = state.plan.tasks
        workers: List[Send] = []

        # batch tasks to reduce GPU calls
        for task in tasks:

            workers.append(
                Send(
                    "worker",
                    {
                        "task": task,
                        "blog_topic": state.blog_topic,
                        "plan": state.plan,
                        "audience": state.audience,
                        "tone": state.tone,
                        'evidence' : state.evidence  
                    },
                )
            )

        return workers

    except Exception as e:
        # this will surface clearly in LangGraph logs
        raise RuntimeError(f"[fanout] failed: {e}") from e

#  5. actual generation of each task seggregated by worker will executed by worker node
async def worker(payload: dict) -> dict:
    try:
        # ---- Validate payload ----
        task = payload["task"]
        if not task:
            raise ValueError("Worker received empty task batch")

        print(f"Worker : Generating sections for task: {getattr(task, 'title', 'unknown')}...\n")

        blog_topic = payload["blog_topic"]
        plan = payload["plan"]
        audience = payload["audience"]
        tone = payload["tone"]
        evidence = payload.get("evidence", [])

        if not blog_topic or not plan:
            raise ValueError("Missing blog topic or plan in worker payload")
        
        if not audience or not tone:
            raise ValueError("Missing audience or tone in worker payload")

        # if not evidence:
        #     raise ValueError("Missing evidence in worker payload")

        # ---- Build prompt for grouped tasks ----
        prompt = worker_prompt(
            task=task,
            blog_topic=blog_topic,
            plan=plan,
            audience=audience,
            tone=tone,
            evidence=evidence,
        )

        # ---- Model inference (GPU-bound) ----
        model = get_generation_model()
        response_msg = await model.ainvoke(prompt)

        content = response_msg.content.strip() #type: ignore
        if not content:
            raise ValueError("Empty response from model")
        
        print(f"Worker : Section generation complete for task: {getattr(task, 'title', 'unknown')}.\n")

        return {"sections": [content]}

    except Exception as e:
        # ---- Graceful fallback ----
        
        task = payload["task"]

        print(f"Worker : Error generating sections for task: {getattr(task, 'title', 'unknown')}. Error: {e}\n")

        error_section = (
            f"## ⚠️ Section generation failed\n\n"
            f"**Affected sections:** {getattr(task, 'title', 'unknown')}\n\n"
            f"**Error:** {str(e)}\n\n"
            f"**Trace (truncated):**\n"
        )

        # IMPORTANT:
        # We return a section instead of raising
        # so the reducer and graph can continue
        return {"sections": [error_section]}

#  6. reducer to aggregate all sections from workers into final blog
async def reducer(state:BlogState):
    try:   

        print("Reducer : Aggregating sections from workers...\n")
        title = state.blog_title or "Untitled Blog"
        blog = "\n\n".join(state.sections)

        final_blog = f"# {title}\n\n{blog}"

        file_name = safe_filename(title)
        print(f"Saving final blog to {file_name}...\n")

        with open(file_name, "w", encoding="utf-8") as f:
            f.write(final_blog)

        print(f"Reducer : Final blog aggregation complete and saved to {file_name}.\n")
        return {'final_blog': final_blog}
    except Exception as e:
        print(f"Error in reducer: {e}")
        raise e

#  7. HITL publish node – asks user whether to post blog to Feather Feable
async def publish_node(state: BlogState) -> dict:
    """Human-in-the-loop node: interrupt the graph and wait for the user
    to decide whether to publish the blog to Feather Feable."""
    try:
        print("Publish_node : Waiting for user decision on publishing...\n")

        # ---- Interrupt – control returns to the client ----
        user_response = interrupt({
            "question": "Do you want to publish this blog to Feather Feable blog web app?",
            "options": ["yes", "no"]
        })

        # ---- User chose to publish ----
        if isinstance(user_response, dict) and user_response.get("approved"):
            access_token = user_response.get("access_token", "")
            if not access_token:
                print("Publish_node : No access token provided. Skipping publish.\n")
                return {"publish_result": "❌ Publishing skipped: No access token provided."}

            print("Publish_node : Publishing blog to Feather Feable...\n")
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "http://localhost:8080/api/v1/blog/auto-blog",
                    headers={
                        "Authorization": f"Bearer {access_token}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "title": state.blog_title or "Untitled Blog",
                        "tags": ["ai", "auto-generated"],
                        "des": (state.blog_topic or "")[:250],
                        "markdown": state.final_blog,
                    },
                    timeout=30.0,
                )

            if response.status_code in (200, 201):
                print(f"Publish_node : Blog published successfully! Status: {response.status_code}\n")
                return {"publish_result": f"✅ Blog published successfully! (HTTP {response.status_code})"}
            else:
                print(f"Publish_node : Publishing failed. Status: {response.status_code}\n")
                return {
                    "publish_result": (
                        f"❌ Publishing failed. HTTP {response.status_code} — "
                        f"{response.text[:300]}"
                    )
                }

        # ---- User chose NOT to publish ----
        else:
            print("Publish_node : User skipped publishing.\n")
            return {"publish_result": "⏭️ Publishing skipped by user."}

    except httpx.RequestError as e:
        print(f"Publish_node : Network error during publishing: {e}\n")
        return {"publish_result": f"❌ Network error: {str(e)}"}
    except GraphInterrupt:
        raise  # Let the interrupt propagate to pause the graph
    except Exception as e:
        print(f"Publish_node : Unexpected error: {e}\n")
        return {"publish_result": f"❌ Unexpected error: {str(e)}"}
    

