from langchain.messages import AIMessage, HumanMessage

from models import structured_output_model, get_generation_model,research_structured_output_model, structured_output_model_research
from states import BlogState, EvidencePackSchema, PlanSchema, ResearchSchema
from prompts.generation_prompts import get_blog_planning_prompt, worker_prompt,get_router_prompt, get_evidence_research_prompt
from typing import Dict, List, cast
from langgraph.types import Send, interrupt
from langgraph.errors import GraphInterrupt
import httpx
import logging

logger = logging.getLogger(__name__)

from utils import normalize_tavily_results, perform_research, safe_filename, with_retry



#  1. get the blog_topic and other details from initial state

async def router_node(state: BlogState) -> dict:
    prompt = get_router_prompt(state.user_query)

    response = await with_retry(
        fn=lambda: research_structured_output_model.ainvoke(prompt),
        fallback=None,
        label="router_node/detail_extraction",
    )

    if response is None:
        logger.error("router_node: detail extraction failed after all retries")
        raise RuntimeError("Failed to extract blog details after all retries.")

    response = cast(ResearchSchema, response)
    logger.info("router_node: detail extraction complete. topic=%s", response.topic)

    return {
        "blog_topic":        response.topic,          # type: ignore
        "audience":          response.audience,        # type: ignore
        "tone":              response.tone,            # type: ignore
        "require_research":  response.require_research,# type: ignore
        "research_mode":     response.research_mode,  # type: ignore
        "research_queries":  response.research_queries,# type: ignore
        "blog_kind":         response.blog_kind,       # type: ignore
    }

# Routing Conditon
def router_condition_func(state: BlogState) -> str:
    if state.require_research:
        return 'research_node'
    else:
        # return END
        return 'orchestrator'


# 2. Research_node
async def research_node(state: BlogState) -> dict:
    queries = state.research_queries or []
    raw_result: List[Dict] = []

    for query in queries:
        try:
            result = await perform_research(query)
            raw_result.extend(result.get("results", []))
        except Exception as e:
            logger.warning("research_node: query failed, skipping. query=%s error=%s", query, e)
            continue

    if not raw_result:
        logger.warning("research_node: no results collected, proceeding without evidence")
        return {'evidence': []}

    # Deduplicate by URL
    unique_results = {}
    for r in raw_result:
        url = r.get("url")
        if url not in unique_results:
            unique_results[url] = r

    deduplicated_list = list(unique_results.values())

    # Normalize the results into a consistent format
    normalized_results = normalize_tavily_results(deduplicated_list)

    # Get the prompt for evidence extraction
    evidence_research_prompt = get_evidence_research_prompt(normalized_results)

    response = await with_retry(
        fn=lambda: structured_output_model_research.ainvoke(evidence_research_prompt),
        fallback=None,
        label="research_node/structured_output",
    )

    if response is None:
        logger.error("research_node: structured output failed, proceeding without evidence")
        return {"evidence": []}

    return {"evidence": cast(EvidencePackSchema, response).evidence}  # type: ignore




#  3. Orchestration logic for the blog planning process
async def orchestrator(state: BlogState):
    blog_topic       = state.blog_topic
    blog_description = state.user_query
    blog_audience    = state.audience
    blog_tone        = state.tone
    blog_evidence    = state.evidence

    prompt = get_blog_planning_prompt(
        blog_topic, blog_description, blog_audience, blog_tone, blog_evidence
    )

    response = await with_retry(
        fn=lambda: structured_output_model.ainvoke(prompt),
        fallback=None,
        label="orchestrator/blog_plan",
    )

    if response is None:
        logger.error("orchestrator: blog plan generation failed after all retries")
        raise RuntimeError("Failed to generate blog plan after all retries.")

    response = cast(PlanSchema, response)
    logger.info("orchestrator: blog plan generation complete. title=%s", response.blog_title)
    return {"plan": response, "blog_title": response.blog_title}  # type: ignore

# create worker to parallely execute the tasks in the plan generated by orchestrator
def fanout(state: BlogState) -> List[Send]:
    try:
        if not state.plan or not state.plan.tasks:
            raise ValueError("No plan or tasks found in state")

        tasks = state.plan.tasks
        workers: List[Send] = []

        # batch tasks to reduce GPU calls
        for task in tasks:

            workers.append(
                Send(
                    "worker",
                    {
                        "task": task,
                        "blog_topic": state.blog_topic,
                        "plan": state.plan,
                        "audience": state.audience,
                        "tone": state.tone,
                        'evidence' : state.evidence  
                    },
                )
            )

        return workers

    except Exception as e:
        # this will surface clearly in LangGraph logs
        raise RuntimeError(f"[fanout] failed: {e}") from e

#  5. actual generation of each task seggregated by worker will executed by worker node
async def worker(payload: dict) -> dict:
    # ---- Validate payload (not retryable) ----
    task = payload.get("task")
    if not task:
        logger.error("worker: empty task received")
        return {"sections": []}

    blog_topic = payload.get("blog_topic")
    plan       = payload.get("plan")
    audience   = payload.get("audience")
    tone       = payload.get("tone")
    evidence   = payload.get("evidence", [])

    if not blog_topic or not plan:
        logger.error("worker: missing blog_topic or plan for task=%s", getattr(task, "title", "unknown"))
        return {"sections": []}

    if not audience or not tone:
        logger.error("worker: missing audience or tone for task=%s", getattr(task, "title", "unknown"))
        return {"sections": []}

    # ---- Build prompt ----
    prompt = worker_prompt(
        task=task,
        blog_topic=blog_topic,
        plan=plan,
        audience=audience,
        tone=tone,
        evidence=evidence,
    )

    # ---- Model inference with retry ----
    async def generate() -> str:
        model = get_generation_model()
        response_msg = await model.ainvoke(prompt)
        content = response_msg.content.strip()  # type: ignore
        if not content:
            raise ValueError("Empty response from model")
        return content

    content = await with_retry(
        fn=generate,
        fallback="",
        label=f"worker/{getattr(task, 'title', 'unknown')}",
    )

    if not content:
        logger.error("worker: generation failed for task=%s", getattr(task, "title", "unknown"))
        return {"sections": []}

    return {"sections": [content]}

#  6. reducer to aggregate all sections from workers into final blog
async def reducer(state: BlogState):
    title      = state.blog_title or "Untitled Blog"
    blog       = "\n\n".join(state.sections)
    final_blog = f"# {title}\n\n{blog}"

    file_name = safe_filename(title)
    with open(file_name, "w", encoding="utf-8") as f:
        f.write(final_blog)

    # ── Build a cheap structural summary instead of full blog ──
    section_titles = [
        getattr(task, "title", f"Section {i+1}")
        for i, task in enumerate(state.plan.tasks or [])
    ] if state.plan else []

    section_list = "\n".join(f"  - {t}" for t in section_titles)

    # blog_context_message = HumanMessage(
    #     content=(
    #         f"[SYSTEM CONTEXT]\n"
    #         f"A blog has been generated with the following structure:\n"
    #         f"Title: {title}\n"
    #         f"Topic: {state.blog_topic}\n"
    #         f"Audience: {state.audience}\n"
    #         f"Tone: {state.tone}\n"
    #         f"Sections:\n{section_list}\n\n"
    #         f"The full blog is stored separately. "
    #         f"If the user asks to refine a specific section, "
    #         f"that section's content will be provided to you."
    #     )
    # )

    assistant_message = AIMessage(
        content=(
            f"Your blog **{title}** has been generated successfully! "
            f"You can read it in the panel below. "
            f"Feel free to ask me to refine any section or make changes."
        )
    )

    logger.info("reducer: final blog assembled. title=%s", title)

    return {
        "final_blog": final_blog,
        "sections":   [],
        "messages":   [assistant_message],
    }
#  7. HITL publish node – asks user whether to post blog to Feather Feable
async def publish_node(state: BlogState) -> dict:
    """Human-in-the-loop node: interrupt the graph and wait for the user
    to decide whether to publish the blog to Feather Feable."""
    try:
        print("Publish_node : Waiting for user decision on publishing...\n")

        # ---- Interrupt – control returns to the client ----
        user_response = interrupt({
            "question": "Do you want to publish this blog to Feather Feable blog web app?",
            "options": ["yes", "no"]
        })

        # ---- User chose to publish ----
        if isinstance(user_response, dict) and user_response.get("approved"):
            access_token = user_response.get("access_token", "")
            if not access_token:
                print("Publish_node : No access token provided. Skipping publish.\n")
                return {"publish_result": "❌ Publishing skipped: No access token provided."}

            print("Publish_node : Publishing blog to Feather Feable...\n")
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "http://localhost:8080/api/v1/blog/auto-blog",
                    headers={
                        "Authorization": f"Bearer {access_token}",
                        "Content-Type": "application/json",
                    },
                    json={
                        "title": state.blog_title or "Untitled Blog",
                        "tags": ["ai", "auto-generated"],
                        "des": (state.blog_topic or "")[:250],
                        "markdown": state.final_blog,
                    },
                    timeout=30.0,
                )

            if response.status_code in (200, 201):
                print(f"Publish_node : Blog published successfully! Status: {response.status_code}\n")
                return {"publish_result": f"✅ Blog published successfully! (HTTP {response.status_code})"}
            else:
                print(f"Publish_node : Publishing failed. Status: {response.status_code}\n")
                return {
                    "publish_result": (
                        f"❌ Publishing failed. HTTP {response.status_code} — "
                        f"{response.text[:300]}"
                    )
                }

        # ---- User chose NOT to publish ----
        else:
            print("Publish_node : User skipped publishing.\n")
            return {"publish_result": "⏭️ Publishing skipped by user."}

    except httpx.RequestError as e:
        print(f"Publish_node : Network error during publishing: {e}\n")
        return {"publish_result": f"❌ Network error: {str(e)}"}
    except GraphInterrupt:
        raise  # Let the interrupt propagate to pause the graph
    except Exception as e:
        print(f"Publish_node : Unexpected error: {e}\n")
        return {"publish_result": f"❌ Unexpected error: {str(e)}"}
    

